### ISSUE TITLE
Aryan where you at?

### ISSUE THREAD

**Issue by zenoix** [aryan-debug/whisp#1]
Hey Aryan,

Hope everything is ok. We miss you bro. When will you be coming back?

**Comment by aryan-debug** [comment]
I will come back after my semester ends :)

**Comment by aryan-debug** [comment]
Hi Wang,

Thanks for asking :) I will come back after my semester ends. Sorry, I left
you guys without explaining anything. It's just that my marks dropped and I
got angry at myself, so I decided to leave. I miss you guys too 🥲. But I
will be back.
